version: '3.9'
networks:
  db_app: 
    driver: bridge
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - config.env
    networks:
      - db_app
    volumes:
      - ./postgres/migration:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - "./config/provisioning:/etc/grafana/provisioning"
      - "./config/custom.ini:/etc/grafana/custom.ini"
      - "./dashboards:/var/lib/grafana/dashboards"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:12345678@postgres:5432/shop?sslmode=disable"
    links:
      - postgres
      - prometheus
